= Robô "Chupa Cabra" para dados disponibilizados pelo SISAM/INPE
:toc: left
:toc-title: Conteúdo
:icons: font
:numbered:
:idprefix:
:idseparator: -
:sectanchors:

:Docker: https://docker.com[Docker^]

== Introdução

Este projeto cria um robô para a extração dos dados de queimadas
disponibilizados pelo SISAM/INPE.
Esses dados podem ser obtidos de forma manual através da página
http://queimadas.dgi.inpe.br/queimadas/sisam/v2/dados/download/

== Pré-requisitos

=== macOS

* Bash (>= 5)
* curl
* gdate (pacote coreutils)
* 7z (pacote p7zip)

=== Ubuntu

* Bash (>= 5)
* curl
* 7z (pacote p7zip-full)

=== Windows

* {Docker}

== Execução direta (através do script)

Nesta versão, o robô pode ser iniciado assim:

----
$ ./chupa-cabra.sh [uf1 uf2 ...]
----

A execução acima fará o download (simultâneo) das informações de duas
UFs por vez até o fim da lista configurada em `ufs.txt` OU, caso sejam
informadas uma ou mais UFs como parâmetro, será feito o dowload das
informações apenas dessas.

NOTE: Um arquivo de log `chupa-cabra.<timestamp>.log` guardará toda a
saída produzida na execução do script.

Neste próximo exemplo, será realizado o download simultâneo (em
paralelo) das informações de quatro UFs por vês (antes de serem
realizados os downloads das próximass UFs da lista configurada em
`ufs.txt`):

----
$ PARALLEL=4 ./chupa-cabra.sh
----

Neste último exemplo, serão realizados downloads apenas para os dois
primeiros anos (e dois primeiros meses) de apenas cinco UFs, com
três execuções ocorrendo de forma paralela (a última, obviamente, terá
duas execuções simultâneas):

----
$ echo "12 27 16 13 29" > ufs.txt
$ PARALLEL=3 FINAL_YEAR=2001 FINAL_MONTH=02 ./chupa-cabra.sh
----

Leia o script link:chupa-cabra.sh[] para entender os detalhes.

== Execução via Docker

----
$ docker run -it --rm -v "$PWD":/data paulojeronimo/sisam-inpe-queimadas-downloader
----
